In [1]:
from __future__ import annotations

from anndata import read_h5ad
from lets_plot import *

LetsPlot.setup_html()
import cellestial as cl

In [2]:
data = read_h5ad("data/pbmc3k_pped.h5ad")

In [3]:
cl.build_frame(data,axis=0,include_dimensions=250)

shape: (16_680, 75)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ barcode    ┆ sample ┆ n_genes_by ┆ log1p_n_g ┆ … ┆ X_TSNE1   ┆ X_TSNE2   ┆ X_UMAP1   ┆ X_UMAP2   │
│ ---        ┆ ---    ┆ _counts    ┆ enes_by_c ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ cat    ┆ ---        ┆ ounts     ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
│            ┆        ┆ i32        ┆ ---       ┆   ┆           ┆           ┆           ┆           │
│            ┆        ┆            ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AAACCCAAGG ┆ s1d1   ┆ 2103       ┆ 7.651596  ┆ … ┆ -8.471021 ┆ 0.673473  ┆ 10.702534 ┆ 1.695078  │
│ ATGGCT-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ AAACCCAAGG ┆ s1d1   ┆ 3916       ┆ 8.273081  ┆ … ┆ 29.971619 ┆ 56.412766 ┆ 11.321092 ┆ 12.690719 │
│ CCTAGA-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ AAACCCAAGT ┆ s1d1   ┆ 683        ┆ 6.527958  ┆ … ┆ -24.18038 ┆ -50.45989 ┆ 17.653606 ┆ -4.508063 │
│ GAGTGC-1   ┆        ┆            ┆           ┆   ┆ 9         ┆ 2         ┆           ┆           │
│ AAACCCACAA ┆ s1d1   ┆ 4330       ┆ 8.373554  ┆ … ┆ 87.926956 ┆ -11.02090 ┆ 16.198011 ┆ 9.535324  │
│ GAGGCT-1   ┆        ┆            ┆           ┆   ┆           ┆ 5         ┆           ┆           │
│ AAACCCACAT ┆ s1d1   ┆ 325        ┆ 5.786897  ┆ … ┆ 39.142281 ┆ -29.90740 ┆ 4.73343   ┆ 4.918097  │
│ CGTGGC-1   ┆        ┆            ┆           ┆   ┆           ┆ 8         ┆           ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ TTTGTTGAGA ┆ s1d3   ┆ 277        ┆ 5.627621  ┆ … ┆ 40.710785 ┆ -25.96138 ┆ 4.593059  ┆ 5.496218  │
│ GTCTGG-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ TTTGTTGCAG ┆ s1d3   ┆ 3797       ┆ 8.24223   ┆ … ┆ 44.826817 ┆ 54.70023  ┆ 14.746174 ┆ 10.975466 │
│ ACAATA-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ TTTGTTGCAT ┆ s1d3   ┆ 3089       ┆ 8.035926  ┆ … ┆ 6.905839  ┆ 86.35585  ┆ 6.338337  ┆ 13.23038  │
│ GTTACG-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ TTTGTTGGTA ┆ s1d3   ┆ 379        ┆ 5.940171  ┆ … ┆ 33.941563 ┆ 3.759629  ┆ 10.61078  ┆ 6.063466  │
│ GTCACT-1   ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ TTTGTTGTCG ┆ s1d3   ┆ 1599       ┆ 7.377759  ┆ … ┆ -12.52451 ┆ 11.060594 ┆ 10.837057 ┆ -0.701824 │
│ CGCTGA-1   ┆        ┆            ┆           ┆   ┆ 3         ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
cl.build_frame(data,axis=1,include_dimensions=20)

shape: (2_000, 37)
┌────────────┬───────┬───────┬───────┬───┬───────────┬───────────┬───────────┬───────────┐
│ variable   ┆ mt    ┆ ribo  ┆ hb    ┆ … ┆ PCS17     ┆ PCS18     ┆ PCS19     ┆ PCS20     │
│ ---        ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ bool  ┆ bool  ┆ bool  ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪═══════╪═══════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AL390719.2 ┆ false ┆ false ┆ false ┆ … ┆ 0.000592  ┆ 0.000521  ┆ -0.000477 ┆ -0.000384 │
│ C1QTNF12   ┆ false ┆ false ┆ false ┆ … ┆ -0.006791 ┆ -0.001876 ┆ 0.001695  ┆ 0.005245  │
│ AL162741.1 ┆ false ┆ false ┆ false ┆ … ┆ -0.001654 ┆ 0.003159  ┆ -0.000388 ┆ 0.001114  │
│ LINC01786  ┆ false ┆ false ┆ false ┆ … ┆ 0.000801  ┆ -0.000601 ┆ 0.001574  ┆ -0.000991 │
│ AL391244.2 ┆ false ┆ false ┆ false ┆ … ┆ -0.001865 ┆ -0.003884 ┆ -0.003769 ┆ 0.003923  │
│ …          ┆ …     ┆ …     ┆ …     ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ PRKY       ┆ false ┆ false ┆ false ┆ … ┆ -0.012667 ┆ -0.055532 ┆ -0.021518 ┆ 0.04266   │
│ KDM5D      ┆ false ┆ false ┆ false ┆ … ┆ 0.007467  ┆ -0.010181 ┆ 0.036239  ┆ 0.017112  │
│ TTTY10     ┆ false ┆ false ┆ false ┆ … ┆ -0.01131  ┆ -0.004084 ┆ 0.002347  ┆ 0.005591  │
│ MT-ND2     ┆ true  ┆ false ┆ false ┆ … ┆ 0.039251  ┆ 0.136351  ┆ 0.034785  ┆ -0.010587 │
│ MT-ND5     ┆ true  ┆ false ┆ false ┆ … ┆ 0.045816  ┆ 0.130208  ┆ 0.036777  ┆ -0.019719 │
└────────────┴───────┴───────┴───────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
for x in data.obsm:
    print(data.obsm[x].shape)

(16680, 50)
(16680, 2)
(16680, 2)

In [8]:
type((1,2))

tuple

In [9]:
a = (1,2)
max(a)

2